# Site settings
title: trop.in
email: andrewtropin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Andrew's blog
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://trop.in" # the base hostname & protocol for your site
twitter_username: 'andrewtropin'
github_username: abcdw
superuser: Andrew Tropin

# Build settings

markdown: kramdown
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "tables", "underline", "highlight", "quote", "footnotes"]

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-gist
