# Site settings
title: trop.in
email: andrewtropin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    just another clojure, emacs, vim, linux, opensource, self-improvement blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trop.in" # the base hostname & protocol for your site
twitter_username: 'andrewtropin'
github_username: abcdw
superuser: Andrew Tropin

# Build settings

markdown: kramdown
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "tables", "underline", "highlight", "quote", "footnotes"]

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-gist
